# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji
  
# Site settings
title: "Hannes Van De Vreken"
description: >
    Working as a web developer.
    On his blog he writes about things he learned while experimenting
    with tools he might use to speed up his development.

email: vandevreken.hannes@gmail.com

# blog logo
author_logo: "/assets/images/author.jpg"
logo: "/assets/images/logo.jpg"

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Hannes Van De Vreken'
author: 'Hannes Van De Vreken'
author_image: "/assets/images/author.jpg"

paginate: 5

url: "https://hannesvdvreken.com"
baseurl: ""
permalink: /:year/:month/:day/:title/

# social icons and sharing options
social:
  - icon: twitter
    url: https://twitter.com/hannesvdvreken
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon: github
    url: https://github.com/hannesvdvreken
    desc: Follow me on github
    share_url:
    share_title:
    share_link:
