# Site settings
title: "Hannes Van De Vreken"
description: >
    Working as a web developer.
    On his blog he writes about things he learned while experimenting
    with tools he might use to speed up his development.

name: 'Hannes Van De Vreken'
author: 'Hannes Van De Vreken'
author_image: "/assets/images/author.jpg"
logo: "/assets/images/logo.jpg"
cover: "/assets/images/banner.jpg"
email: vandevreken.hannes@gmail.com
env: production

url: "https://hannesvdvreken.com"
baseurl: ""
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown
highlighter: pygments
gems:
  - jemoji

paginate: 5
paginate_path: "/page/:num"

# Google analytics
ga:
  tracking: UA-9732394-15

# Disqus
disqus:
  shortname: hannesvdvreken

# GitHub
github:
  repo: hannesvdvreken/hannesvdvreken.github.io

# Twitter
twitter:
  handle: hannesvdvreken

# Add is_post to posts
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      is_post: true

# social icons and sharing options
social:
  - icon: twitter
    url: https://twitter.com/hannesvdvreken
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon: github
    url: https://github.com/hannesvdvreken
    desc: Follow me on github

  - icon: instagram
    url: https://instagram.com/hannesvdvreken
    desc: Watch my pictures on Instagram
