# Site settings
title: Hannes Van De Vreken
email: vandevreken.hannes@gmail.com
description: "Hannes is a web developer. On his blog he writes about things he learned while experimenting with tools he might use to speed up his development."
skills: "Web developer at <a href='http://mwl.be'>madewithlove</a>"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F
  white: ffffff

nav:
  posts: Posts
  about: About
  contact: Contact

# Footer settings
footer:
  copyright: Hannes Van De Vreken
  location: Location
  social: You can find me here
  credits: About me

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/hannesvdvreken
  - title: twitter
    url: https://twitter.com/hannesvdvreken
  - title: stack-overflow
    url: https://stackoverflow.com/users/1079360/hannesvdvreken
  - title: instagram
    url: https://instagram.com/hannesvdvreken

# Google analytics
ga:
  tracking: UA-9732394-15

# Postal address (add as many lines as necessary)
address:
  - line: Ghent, Antwerp, Leuven, Brussels
  - line: Belgium

# Credits content
credits: 'I am a web developer interested in modern PHP development, node.js and all web things standardised.'

# Build settings
markdown: kramdown
markdown_ext: md
permalink: pretty
enable_coderay: true